# Generated by Django 3.0.3 on 2020-05-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='special',
            name='friday',
        ),
        migrations.RemoveField(
            model_name='special',
            name='monday',
        ),
        migrations.RemoveField(
            model_name='special',
            name='saturday',
        ),
        migrations.RemoveField(
            model_name='special',
            name='sunday',
        ),
        migrations.RemoveField(
            model_name='special',
            name='thursday',
        ),
        migrations.RemoveField(
            model_name='special',
            name='tuesday',
        ),
        migrations.RemoveField(
            model_name='special',
            name='wednesday',
        ),
        migrations.AddField(
            model_name='special',
            name='day',
            field=models.CharField(choices=[('monday', 'monday'), ('tuesday', 'tuesday'), ('wednesday', 'wednesday'), ('thursday', 'thursday'), ('friday', 'friday'), ('saturday', 'saturday'), ('sunday', 'sunday')], default='', max_length=10),
        ),
    ]
