# Generated by Django 3.0.3 on 2020-05-10 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200510_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='special',
            name='every_day',
        ),
        migrations.AlterField(
            model_name='special',
            name='day',
            field=models.CharField(choices=[('All Days', 'All Days'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='All Days', max_length=10),
        ),
    ]
